# Generated by Django 5.1.2 on 2025-04-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountNumberTracker",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_account_number", models.PositiveIntegerField(default=100000)),
            ],
        ),
        migrations.CreateModel(
            name="AccountType",
            fields=[
                ("accountTypeID", models.AutoField(primary_key=True, serialize=False)),
                ("depositType", models.CharField(max_length=100)),
                ("depositRates", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("adminID", models.AutoField(primary_key=True, serialize=False)),
                ("department", models.CharField(max_length=100)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                ("customerID", models.AutoField(primary_key=True, serialize=False)),
                ("beneficiary", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Loans",
            fields=[
                ("loanID", models.AutoField(primary_key=True, serialize=False)),
                ("loanType", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("interestRate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "minAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "maxAmount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("minTerm", models.IntegerField(blank=True, null=True)),
                ("maxTerm", models.IntegerField(blank=True, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True, null=True)),
                ("requirements", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                (
                    "transactionTypeID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "transactionType",
                    models.CharField(
                        choices=[
                            ("withdraw", "Withdraw"),
                            ("deposit", "Deposit"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phoneNumber", models.CharField(max_length=15, unique=True)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("provinces", models.CharField(max_length=50)),
                ("dateOfBirth", models.DateField(blank=True, null=True)),
                ("panNumber", models.CharField(max_length=20, unique=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "accountNumber",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "accountNumber",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "accountTypeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.accounttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoanAccount",
            fields=[
                ("loan_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("outstanding", models.DecimalField(decimal_places=2, max_digits=15)),
                ("term", models.IntegerField()),
                ("start_date", models.DateField()),
                ("next_payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("paid", "Paid Off"),
                            ("defaulted", "Defaulted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        db_column="account_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_accounts",
                        to="users.account",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.loans",
                    ),
                ),
            ],
            options={
                "db_table": "users_loanaccount",
            },
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                ("transactionID", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reference", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "accountID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.account"
                    ),
                ),
                (
                    "transactionTypeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.transactiontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Withdraw",
            fields=[
                ("withdrawID", models.AutoField(primary_key=True, serialize=False)),
                ("home", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("last_location", models.CharField(max_length=255)),
                ("retailer", models.CharField(blank=True, max_length=255, null=True)),
                ("repeat_retailer", models.BooleanField(default=False)),
                ("used_chip", models.BooleanField(default=False)),
                ("used_pin", models.BooleanField(default=True)),
                ("online_order", models.BooleanField(default=False)),
                (
                    "withdrawal_type",
                    models.CharField(
                        choices=[
                            ("atm", "ATM Withdrawal"),
                            ("online_order", "Online Order"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdraw",
                        to="users.transactions",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
