# Generated by Django 5.1.2 on 2025-03-11 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountNumberTracker",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_account_number", models.PositiveIntegerField(default=100000)),
            ],
        ),
        migrations.CreateModel(
            name="AccountType",
            fields=[
                ("accountTypeID", models.AutoField(primary_key=True, serialize=False)),
                ("depositType", models.CharField(max_length=100)),
                ("depositRates", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("adminID", models.AutoField(primary_key=True, serialize=False)),
                ("department", models.CharField(max_length=100)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                ("customerID", models.AutoField(primary_key=True, serialize=False)),
                ("beneficiary", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Loans",
            fields=[
                ("loanID", models.AutoField(primary_key=True, serialize=False)),
                ("loanTypes", models.CharField(max_length=100)),
                ("interestRates", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionType",
            fields=[
                (
                    "transactionTypeID",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "transactionType",
                    models.CharField(
                        choices=[
                            ("withdraw", "Withdraw"),
                            ("deposit", "Deposit"),
                            ("transfer", "Transfer"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phoneNumber", models.CharField(max_length=15, unique=True)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("provinces", models.CharField(max_length=50)),
                ("dateOfBirth", models.DateField(blank=True, null=True)),
                ("panNumber", models.CharField(max_length=20, unique=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "accountNumber",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=15),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "accountNumber",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "accountTypeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.accounttype",
                    ),
                ),
                (
                    "loanID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.loans",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transactions",
            fields=[
                ("transactionID", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reference", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=15, null=True),
                ),
                (
                    "accountID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.account"
                    ),
                ),
                (
                    "transactionTypeID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.transactiontype",
                    ),
                ),
            ],
        ),
    ]
