# Generated by Django 5.1.2 on 2025-04-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SIPCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_investment", models.FloatField()),
                ("annual_return", models.FloatField()),
                ("years", models.IntegerField()),
                ("total_expected_returns", models.FloatField()),
                ("total_invested", models.FloatField()),
                ("total_gain", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
