# Generated by Django 5.1.2 on 2025-03-14 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_account_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdraw",
            fields=[
                ("withdrawID", models.AutoField(primary_key=True, serialize=False)),
                ("home", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("last_location", models.CharField(max_length=255)),
                ("retailer", models.CharField(blank=True, max_length=255, null=True)),
                ("repeat_retailer", models.BooleanField(default=False)),
                ("used_chip", models.BooleanField(default=False)),
                ("used_pin", models.BooleanField(default=True)),
                ("online_order", models.BooleanField(default=False)),
                (
                    "withdrawal_type",
                    models.CharField(
                        choices=[
                            ("atm", "ATM Withdrawal"),
                            ("online_order", "Online Order"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdraw",
                        to="users.transactions",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
