# Generated by Django 5.1.2 on 2025-03-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_withdraw"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loans",
            old_name="interestRates",
            new_name="interestRate",
        ),
        migrations.RenameField(
            model_name="loans",
            old_name="loanTypes",
            new_name="loanType",
        ),
        migrations.AddField(
            model_name="loans",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="loans",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loans",
            name="maxAmount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="loans",
            name="maxTerm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loans",
            name="minAmount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="loans",
            name="minTerm",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
