# Generated by Django 5.1.2 on 2025-04-12 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_chatconversation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="loanID",
        ),
        migrations.AddField(
            model_name="loans",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="LoanAccount",
            fields=[
                ("loan_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("outstanding", models.DecimalField(decimal_places=2, max_digits=15)),
                ("term", models.IntegerField()),
                ("start_date", models.DateField()),
                ("next_payment_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("paid", "Paid Off"),
                            ("defaulted", "Defaulted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="users.account",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.loans"
                    ),
                ),
            ],
        ),
    ]
