# Generated by Django 5.1.2 on 2025-04-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_account_loanid_loans_is_active_loanaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="loans",
            name="requirements",
            field=models.TextField(blank=True, null=True),
        ),
    ]
